// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/gateway-boss.proto

package bosspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Taskname      string                 `protobuf:"bytes,2,opt,name=taskname,proto3" json:"taskname,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Tokens        []string               `protobuf:"bytes,5,rep,name=tokens,proto3" json:"tokens,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_proto_gateway_boss_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_boss_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_gateway_boss_proto_rawDescGZIP(), []int{0}
}

func (x *TaskRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *TaskRequest) GetTaskname() string {
	if x != nil {
		return x.Taskname
	}
	return ""
}

func (x *TaskRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TaskRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TaskRequest) GetTokens() []string {
	if x != nil {
		return x.Tokens
	}
	return nil
}

func (x *TaskRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type TaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Taskname      string                 `protobuf:"bytes,1,opt,name=taskname,proto3" json:"taskname,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Solution      []byte                 `protobuf:"bytes,4,opt,name=solution,proto3" json:"solution,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ArchiveSize   int64                  `protobuf:"varint,7,opt,name=archive_size,json=archiveSize,proto3" json:"archive_size,omitempty"`
	ArchiveFormat string                 `protobuf:"bytes,8,opt,name=archive_format,json=archiveFormat,proto3" json:"archive_format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	mi := &file_proto_gateway_boss_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_boss_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_gateway_boss_proto_rawDescGZIP(), []int{1}
}

func (x *TaskResponse) GetTaskname() string {
	if x != nil {
		return x.Taskname
	}
	return ""
}

func (x *TaskResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TaskResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TaskResponse) GetSolution() []byte {
	if x != nil {
		return x.Solution
	}
	return nil
}

func (x *TaskResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TaskResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TaskResponse) GetArchiveSize() int64 {
	if x != nil {
		return x.ArchiveSize
	}
	return 0
}

func (x *TaskResponse) GetArchiveFormat() string {
	if x != nil {
		return x.ArchiveFormat
	}
	return ""
}

var File_proto_gateway_boss_proto protoreflect.FileDescriptor

const file_proto_gateway_boss_proto_rawDesc = "" +
	"\n" +
	"\x18proto/gateway-boss.proto\x12\x04boss\"\x8f\x02\n" +
	"\vTaskRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\btaskname\x18\x02 \x01(\tR\btaskname\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06tokens\x18\x05 \x03(\tR\x06tokens\x12;\n" +
	"\bmetadata\x18\x06 \x03(\v2\x1f.boss.TaskRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x85\x02\n" +
	"\fTaskResponse\x12\x1a\n" +
	"\btaskname\x18\x01 \x01(\tR\btaskname\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bsolution\x18\x04 \x01(\fR\bsolution\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\x12!\n" +
	"\farchive_size\x18\a \x01(\x03R\varchiveSize\x12%\n" +
	"\x0earchive_format\x18\b \x01(\tR\rarchiveFormat2<\n" +
	"\vTaskService\x12-\n" +
	"\x04Task\x12\x11.boss.TaskRequest\x1a\x12.boss.TaskResponseB\x1eZ\x1c./internal/fetcher/grpc/bossb\x06proto3"

var (
	file_proto_gateway_boss_proto_rawDescOnce sync.Once
	file_proto_gateway_boss_proto_rawDescData []byte
)

func file_proto_gateway_boss_proto_rawDescGZIP() []byte {
	file_proto_gateway_boss_proto_rawDescOnce.Do(func() {
		file_proto_gateway_boss_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gateway_boss_proto_rawDesc), len(file_proto_gateway_boss_proto_rawDesc)))
	})
	return file_proto_gateway_boss_proto_rawDescData
}

var file_proto_gateway_boss_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_gateway_boss_proto_goTypes = []any{
	(*TaskRequest)(nil),  // 0: boss.TaskRequest
	(*TaskResponse)(nil), // 1: boss.TaskResponse
	nil,                  // 2: boss.TaskRequest.MetadataEntry
}
var file_proto_gateway_boss_proto_depIdxs = []int32{
	2, // 0: boss.TaskRequest.metadata:type_name -> boss.TaskRequest.MetadataEntry
	0, // 1: boss.TaskService.Task:input_type -> boss.TaskRequest
	1, // 2: boss.TaskService.Task:output_type -> boss.TaskResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_gateway_boss_proto_init() }
func file_proto_gateway_boss_proto_init() {
	if File_proto_gateway_boss_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gateway_boss_proto_rawDesc), len(file_proto_gateway_boss_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_gateway_boss_proto_goTypes,
		DependencyIndexes: file_proto_gateway_boss_proto_depIdxs,
		MessageInfos:      file_proto_gateway_boss_proto_msgTypes,
	}.Build()
	File_proto_gateway_boss_proto = out.File
	file_proto_gateway_boss_proto_goTypes = nil
	file_proto_gateway_boss_proto_depIdxs = nil
}
